### PR TITLE
Use browserslist config for options.browsers

### PR DESCRIPTION
**Pull request by tmpst**
This lets browserslist resolve the configuration object.

### CODE REVIEW

**Comment by tmpst** [comment]
hmmm - not sure what is going on with this. Tests pass locally...

**Comment by ismay** [comment]
@tmpst Thanks for the pr, but resolving a browserslist config is actually already done by doiuse. So we don't need to reimplement it.

**Comment by tmpst** [comment]
doiuse implements its own function for resolving browserlist config and only resolves on `browserlist` as a file name - where you can resolve on end and other file names.  It can't always resolve the file path from within a stylelint plugin (eg within Atom as is my case) which is why I submitted a PR here.

I'm not sure why CI is failing when test passes locally.

**Comment by tmpst** [comment]
"end" = "env" (iPhone autocorrect)

**Comment by ismay** [comment]
> doiuse implements its own function for resolving browserlist config and only resolves on browserlist as a file name - where you can resolve on end and other file names

Not anymore, see here: https://github.com/anandthakker/doiuse/issues/63#issuecomment-286394335

Also, solving this isn't something that we should do in this plugin, it would be better for everyone if we'd solve it in doiuse. There's already an issue open for that in the doiuse repo: https://github.com/anandthakker/doiuse/issues/67. Once it's been solved there we can just update our doiuse version.

(The CI tests are failing because of eslint btw.)

**Comment by tmpst** [comment]
Thanks for hooking me into the doiuse issues

**Comment by ismay** [comment]
No problem. Thanks again for the pr, hope the issue'll be resolved soon.

**Pull request closed without merging**
