### PR TITLE
Upgrade doiuse (4.2.0)

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Comment by ismay** [comment]
Nice, thanks for the update 👍

**Comment by GenaBitu** [comment]
Hi, are you planning on releasing a new version with this?

I've been plagued by anandthakker/doiuse#87 making this plugin unusable...

Thanks!

**Comment by ismay** [comment]
No problem, I’ll do that tomorrow 👍

**Comment by ismay** [comment]
@GenaBitu Published as 3.0.2

**Comment by GenaBitu** [comment]
Hi, thanks!

**Pull request merged**
