### PR TITLE
Update Doiuse for vulnerability fix

### PR DESCRIPTION
**Pull request by jimmybrawn**
New doiuse has been released with a fix in the yargs vulnerability warning

### CODE REVIEW

**Comment by ismay** [comment]
Weird, somehow the travis integration is not being triggered. Is this a security related patch? Or just a fix of something non-critical?

**Comment by jimmybrawn** [comment]
The former 😬 and optimization of package

**Comment by ismay** [comment]
> The former 😬 and optimization of package

Sounds good. Could you change the commit msg to "fix: update doiuse"? That way it'll be released automatically when we merge this (plus it'll hopefully trigger CI as well).

**Pull request merged**
