### PR TITLE
Add support for all CSS features

### PR DESCRIPTION
**Pull request by RJWadley**
This PR updates to my forked version of doiuse that supports all CSS features currently in the caniuse-lite database. The switch is plug and play.

I've submitted a pull request to the original doiuse repo, but it's worth noting that the project isn't actively maintained. I'll be maintaining the forked version for the time being. For more context, or to see a summary of the changes, check out the [relevant pull request](https://github.com/anandthakker/doiuse/pull/159).

### CODE REVIEW

**Comment by RJWadley** [comment]
That sounds great, I'd much prefer to consolidate everything into the original doiuse repository.

All the work I've done has been built on top of the great work clshortfuse has done. For reference, [here's the PR that merges clshortfuse's work](https://github.com/anandthakker/doiuse/pull/157), and [here's one with the changes I've made](https://github.com/anandthakker/doiuse/pull/157).

**Comment by ismay** [comment]
Good to see the work on doiuse progressing! Let me know when https://github.com/anandthakker/doiuse/pull/159 has been merged and we can look at updating doiuse here.

**Comment by ismay** [comment]
Thanks for the work you've put into doiuse @RJWadley!

**Comment by ismay** [comment]
Hey @RJWadley, this is a bit out of the blue, but would you be interested in taking over stylelint-no-unsupported-browser-features? I no longer really have the time to maintain it so I'm looking for a new maintainer. Let me know if you'd be interested!

**Comment by RJWadley** [comment]
Sure, I'd be interested.

**Comment by ismay** [comment]
Nice, that's good to hear. Shall I transfer the GH repo and the npm module to you? I'm assuming https://www.npmjs.com/~rjwadley is your npm account? Let me know what you'd prefer.

**Comment by RJWadley** [comment]
Sure, that sounds good to me. And that is my npm account. Is there anything else I should be aware of?

**Comment by ismay** [comment]
> Is there anything else I should be aware of?

Only these minor things:

- There's a 5.x branch for backports to v5. Someone opened a PR a while back because they were stuck on a particular node version and needed a fix for that version. I opened the branch but didn't hear back from them, so you could just remove it.
- The repo uses [semantic release](https://semantic-release.gitbook.io/semantic-release/) for automated releases, changelog generation, etc. See the action [here](https://github.com/ismay/stylelint-no-unsupported-browser-features/blob/master/.github/workflows/node.yml#L37). This requires two env vars, `GH_TOKEN` and `NPM_TOKEN`. These are tied to my accounts, so I won't transfer them over. If you want to keep the automated releases you can supply your own gh and npm token and it should all work out of the box.
- [Codecov](https://about.codecov.io/) is linked to my gh account. If you want to keep using that you'll need a free account with them.
- The github and codecov badges in the readme link to my gh and codecov account, those will need to be updated.
- I've used [renovate](https://www.mend.io/renovate/) to keep dependencies up to date, config is [here](https://github.com/ismay/stylelint-no-unsupported-browser-features/blob/master/package.json#L71). It's linked to my account, so if you want to continue using it you'll need a free account with them.

The above depends on your preferences of course, you could also use different tooling. I've updated any other things that referred to me, like the package.json author fields, etc. Let me know if you have any questions!

**Comment by ismay** [comment]
Oh one other thing. In order to transfer the repo you'll need to delete your fork of stylelint-no-unsupported-browser-features first. Once you've done that I'll be able to transfer the repo over.

**Comment by ismay** [comment]
> I've deleted my fork. Thanks for all the info.

Sure thing, happy to help 👍. And thank you for adopting the project! I've initiated the transfer of both the npm module and the github repo to your accounts. You should have received notifications for both, let me know if you haven't or if you have questions!

**Comment by ismay** [comment]
All right, that's everything transferred 😊🎉. Feel free to ping me if there's anything I can help out with!

**Pull request closed without merging**
