### PR TITLE
Move stylelint as a peerDependency #50

### PR DESCRIPTION
**Pull request by mike3run**
as discussed in #50

### CODE REVIEW

**Comment by ismay** [comment]
Thanks! Would you mind updating the lockfile and adding an `npm install stylelint` after [this line](https://github.com/mike3run/stylelint-no-unsupported-browser-features/blob/5561a22dedecd49a57778f5f5e981b025076b414/.travis.yml#L13)?

**Comment by mike3run** [comment]
@ismay let me know if those changes are okay

**Comment by mike3run** [comment]
ps: happy new year 👍

**Comment by ismay** [comment]
Hi @mike3run, happy new year to you as well 🎉 ! Thanks for the updates. Almost good to merge, one thing left is the `yarn.lock`. Would you mind removing that? I don't use yarn, so I won't be keeping the lockfile up to date.

**Comment by mike3run** [comment]
all good now.

I read somewhere that lockfiles in libraries are not a good thing because while the authors can use them when installing, the people installing the library might actually just get what's in the package.json and not what's in the lockfile.

So by not having lockfiles you can guarantee having the same dependencies as your users.

It was written by someone much smarter on an amazing project (maybe create-react-app) but i can't remember exactly where it was discussed to link you about it.

Food for thought anyways 😄

**Comment by mike3run** [comment]
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

Soo the TL;DR is that lockfiles are good for projects but not good for library mantainers because users might have a bug you can't see because of here's lockfile.

Again, the actual place where I read it was in a github issue of a top level package but i can't really remember which one was 😢

**Comment by mike3run** [comment]
https://www.npmjs.com/package/remove-lockfiles

**Comment by ismay** [comment]
I wonder if that also counts when you’re using greenkeeper though. Because greenkeeper runs a build for new versions of dependencies (and it updates the lockfile), and tells me when tests have failed.

**Comment by ismay** [comment]
I opened an issue with greenkeeper to verify whether it's ok to commit lockfiles when using greenkeeper: https://github.com/greenkeeperio/greenkeeper/issues/569. Let's see what they recommend, and otherwise I'll remove it.

**Comment by ismay** [comment]
@mike3run, apparently even with greenkeeper (due to an open issue) lockfiles still shouldn’t be committed (see the linked issue). Thanks for the heads up!

**Comment by mike3run** [comment]
😄

**Pull request merged**
